name: jsonable_object
description: A micro plugin that displays interfaces for creating json from an object instance, and building an object instance from a json
version: 1.0.2
homepage: https://github.com/RafaelSilvaPereira/jsonable_object

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
